# Default values for portal-frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: portal
replicaCount: 1

image:
  repository: 777345813910.dkr.ecr.eu-central-1.amazonaws.com/nowar-frontend
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "c06a05ef7b8236b86ba0435ad9ff79eeb18f71e8"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""




service:
  type: NodePort
  port: 80


ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

envs:
  NODE_ENV: develop
  PROTOCOL: 2
  DEIP_CLIENT_URL: https://casimir.one
  DEIP_SERVER_URL: https://backend.casimir.one
  DEIP_WEB_SOCKET_URL: wss://socket.casimir.one
  DEIP_FULL_NODE_URL: wss://ws-appchain.casimir.one
  DEIP_CHAIN_EXPLORER_URL: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fcasimir-sandbox-node.deip.world#/explorer/query/0xa69793f53d75260946c79cb633b4d8990aa42f233453403142ec886caa4be70d
  DEIP_PAYMENT_SERVICE_URL: https://dev-payments.deip.world
  TENANT: "0000000000000000000000000000000000000001"
  SIG_SEED: "quickbrownfoxjumpsoverthelazydog"
  CORE_ASSET: '{ "id": 0, "symbol": "DEIP", "precision": 18 }'
  FAUCET_ACCOUNT_USERNAME: regacc
  ACCOUNT_DEFAULT_FUNDING_AMOUNT: 10000000000000000000000
  APP_ID: 25f9e794323b453885f5181f1b624d0b
  VUE_APP_I18N_LOCALE: en
  VUE_APP_I18N_FALLBACK_LOCALE: en
  TENANT_HOT_WALLET_DAO_ID: 20d1c50067827d1ba447d1be4a4d5129fb0583ed
  WALLET_OAUTH_URL: https://wallet-testnet.deip.world/account/oauth
  WALLET_URL: https://wallet-testnet.deip.world

