apiVersion: v1
kind: Service
metadata:
  name: appchain-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: appchain
  ports:
    - protocol: TCP
      port: 9944
      targetPort: 9944
      name: ws-port
    - protocol: TCP
      port: 9933
      targetPort: 9933
      name: http-port